version: "3.8"
services:
  db:
    image: mysql:8.0
    container_name: my-database
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - myapp-db-data:/var/lib/mysql
    networks:
      - myapp-network
    ports:
      - "3306:3306"
    restart: unless-stopped

  web:
    build: ./app
    container_name: my-webapp
    environment:
      DB_HOST: db
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydb
    depends_on:
      - db
    networks:
      - myapp-network
    ports:
      - "5000:5000"
    restart: unless-stopped

networks:
  myapp-network:

volumes:
  myapp-db-data:

